# Generated by Django 3.2.7 on 2021-09-12 18:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload', models.ImageField(default='image', upload_to='uploads/')),
                ('title', models.CharField(max_length=100)),
                ('characteristics', django_mysql.models.ListCharField(models.CharField(max_length=12), max_length=78, size=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
