# Generated by Django 3.2.7 on 2021-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
