# Generated by Django 3.2.7 on 2021-09-12 03:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='characteristics',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), max_length=30, size=6),
        ),
        migrations.AlterField(
            model_name='img',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
