# Generated by Django 3.2.7 on 2021-09-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0002_img_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image_upload',
            field=models.ImageField(default='image', upload_to='upload/'),
        ),
    ]
