# Generated by Django 3.2.7 on 2021-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0002_auto_20210912_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='upload',
            field=models.ImageField(default='image', upload_to='uploads/'),
        ),
    ]
