# Generated by Django 3.2.7 on 2021-09-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0003_img_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='upload',
            new_name='image_upload',
        ),
    ]
