# Generated by Django 3.2.7 on 2021-09-15 02:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0004_img_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='characteristics',
            field=django_mysql.models.ListCharField(models.CharField(max_length=12), max_length=78, null=True, size=6),
        ),
    ]
