# Generated by Django 3.2.7 on 2021-09-12 17:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0004_rename_upload_img_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='characteristics',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6),
        ),
    ]
