# Generated by Django 3.2.7 on 2021-09-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchImg', '0005_alter_img_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
